### ISSUE TITLE
Temporarily disable and re-enable attraction

### ISSUE THREAD

**Issue by jamiehunterdesign** [bymayo/jquery-attract-hover#2]
What's the best way to temporarily disable attraction and re-enable later? I've tried removing classes and redefining the options but none of them seem to remove the effect.

Thanks, great little effect by the way!

**Comment by bymayo** [comment]
@jamiehunterdesign Whats the use case for this? Why are you trying to disable then re-enable?

**Comment by jamiehunterdesign** [comment]
Once the element is clicked (attract enabled) it resizes and content is revealed below (attract disabled). This content can then be closed and the element returns to its original state (attract enabled).

**Comment by jamiehunterdesign** [comment]
I came up with a solution by toggling 'attract-hover' and 'attract-hover-easing' classes.

**Comment by bymayo** [comment]
Ahh I see! Yeah your best solution here is to just play with the `attract-hover-*` classes and alter it via CSS
